/**
 * practiceQuestionsData.js
 * -------------------------
 * Central data source for the Practice Questions Module.
 * Contains COURSES (all core technical courses) and QUESTIONS
 * (Easy / Medium / Hard for each course).
 *
 * Replace / extend this with real data from your backend or CMS.
 * Each question: { id, courseId, difficulty, title, prompt, options, correctIndex, explanation }
 */

export const COURSES = [
  { id: "java", name: "Java" },
  { id: "python", name: "Python" },
  { id: "c", name: "C" },
  { id: "cpp", name: "C++" },
  { id: "javascript", name: "JavaScript" },
  { id: "dsa", name: "Data Structures" },
  { id: "algorithms", name: "Algorithms" },
  { id: "dbms", name: "DBMS / SQL" },
  { id: "oop", name: "OOP Concepts" },
  { id: "webdev", name: "Web Development" },
  { id: "os", name: "Operating Systems" },
  { id: "networks", name: "Computer Networks" },
];

export const QUESTIONS = [
  // ---------------- JAVA ----------------
  {
    id: "java-e1",
    courseId: "java",
    difficulty: "Easy",
    title: "Hello World Output",
    prompt: "Which method is used to print output to the console in Java?",
    options: ["System.out.println()", "console.log()", "print()", "echo()"],
    correctIndex: 0,
    explanation: "System.out.println() writes text followed by a newline to standard output in Java.",
  },
  {
    id: "java-e2",
    courseId: "java",
    difficulty: "Easy",
    title: "Creating Objects",
    prompt: "Which keyword is used to create a new object in Java?",
    options: ["new", "create", "object", "make"],
    correctIndex: 0,
    explanation: "The 'new' keyword allocates memory and creates an instance of a class.",
  },
  {
    id: "java-e3",
    courseId: "java",
    difficulty: "Easy",
    title: "Primitive Types",
    prompt: "Which of the following is NOT a primitive data type in Java?",
    options: ["int", "boolean", "String", "char"],
    correctIndex: 2,
    explanation: "String is a class (object type) in Java, not a primitive type.",
  },
  {
    id: "java-m1",
    courseId: "java",
    difficulty: "Medium",
    title: "Access Modifiers",
    prompt: "Which access modifier makes a member visible only within its own class?",
    options: ["public", "protected", "private", "default"],
    correctIndex: 2,
    explanation: "private restricts access to within the declaring class only.",
  },
  {
    id: "java-m2",
    courseId: "java",
    difficulty: "Medium",
    title: "Preventing Inheritance",
    prompt: "Which keyword prevents a class from being inherited?",
    options: ["static", "final", "private", "abstract"],
    correctIndex: 1,
    explanation: "A class declared 'final' cannot be extended by any other class.",
  },
  {
    id: "java-m3",
    courseId: "java",
    difficulty: "Medium",
    title: "Creating Threads",
    prompt: "Which interface is commonly implemented to define a task that runs on a thread?",
    options: ["Runnable", "Serializable", "Cloneable", "Comparable"],
    correctIndex: 0,
    explanation: "Implementing Runnable and passing it to a Thread is the standard way to define thread behavior.",
  },
  {
    id: "java-h1",
    courseId: "java",
    difficulty: "Hard",
    title: "Multithreading",
    prompt: "Which keyword ensures only one thread accesses a method/block at a time?",
    options: ["static", "synchronized", "volatile", "final"],
    correctIndex: 1,
    explanation: "synchronized enforces mutual exclusion, allowing only one thread to execute the block/method at a time.",
  },
  {
    id: "java-h2",
    courseId: "java",
    difficulty: "Hard",
    title: "Multiple Inheritance",
    prompt: "How does Java achieve multiple inheritance of type?",
    options: ["Using multiple classes", "Using interfaces", "It is not supported at all", "Using abstract classes only"],
    correctIndex: 1,
    explanation: "A class can implement multiple interfaces, giving Java a form of multiple inheritance of type.",
  },
  {
    id: "java-h3",
    courseId: "java",
    difficulty: "Hard",
    title: "Collections",
    prompt: "Which collection maintains insertion order and allows duplicate elements?",
    options: ["HashSet", "TreeSet", "ArrayList", "HashMap"],
    correctIndex: 2,
    explanation: "ArrayList preserves insertion order and permits duplicate elements.",
  },

  // ---------------- PYTHON ----------------
  {
    id: "python-e1",
    courseId: "python",
    difficulty: "Easy",
    title: "List vs Tuple",
    prompt: "Which of these is immutable in Python?",
    options: ["List", "Dictionary", "Tuple", "Set"],
    correctIndex: 2,
    explanation: "Tuples cannot be changed after creation, unlike lists, sets, or dictionaries.",
  },
  {
    id: "python-e2",
    courseId: "python",
    difficulty: "Easy",
    title: "Print Function",
    prompt: "Which function is used to display output in Python?",
    options: ["print()", "echo()", "display()", "console.log()"],
    correctIndex: 0,
    explanation: "print() outputs text to the console in Python.",
  },
  {
    id: "python-e3",
    courseId: "python",
    difficulty: "Easy",
    title: "Indentation",
    prompt: "What does Python use to define blocks of code instead of braces {}?",
    options: ["Semicolons", "Indentation", "Parentheses", "Keywords"],
    correctIndex: 1,
    explanation: "Python uses consistent indentation to define code blocks such as loops and functions.",
  },
  {
    id: "python-m1",
    courseId: "python",
    difficulty: "Medium",
    title: "List Comprehension",
    prompt: "What does [x*x for x in range(5)] produce?",
    options: ["[0, 1, 4, 9, 16]", "[1, 4, 9, 16, 25]", "[0, 1, 2, 3, 4]", "Error"],
    correctIndex: 0,
    explanation: "It squares each number from 0 to 4, giving [0, 1, 4, 9, 16].",
  },
  {
    id: "python-m2",
    courseId: "python",
    difficulty: "Medium",
    title: "Dictionaries",
    prompt: "Which method returns all keys of a dictionary?",
    options: [".values()", ".items()", ".keys()", ".get()"],
    correctIndex: 2,
    explanation: ".keys() returns a view of all the dictionary's keys.",
  },
  {
    id: "python-m3",
    courseId: "python",
    difficulty: "Medium",
    title: "Exception Handling",
    prompt: "Which block always executes, whether an exception occurs or not?",
    options: ["try", "except", "finally", "raise"],
    correctIndex: 2,
    explanation: "The 'finally' block runs regardless of whether an exception was raised.",
  },
  {
    id: "python-h1",
    courseId: "python",
    difficulty: "Hard",
    title: "Decorators",
    prompt: "What is the primary purpose of a decorator in Python?",
    options: [
      "To modify or extend a function's behavior without changing its code",
      "To declare variable types",
      "To handle exceptions",
      "To import modules",
    ],
    correctIndex: 0,
    explanation: "Decorators wrap a function to add functionality before/after it runs, without modifying its source.",
  },
  {
    id: "python-h2",
    courseId: "python",
    difficulty: "Hard",
    title: "GIL",
    prompt: "What does GIL stand for in CPython?",
    options: ["Global Interface Layer", "Global Interpreter Lock", "General Import Library", "Generic Instance Loader"],
    correctIndex: 1,
    explanation: "The GIL ensures only one thread executes Python bytecode at a time in CPython.",
  },
  {
    id: "python-h3",
    courseId: "python",
    difficulty: "Hard",
    title: "Generators",
    prompt: "Which keyword turns a function into a generator?",
    options: ["return", "yield", "async", "lambda"],
    correctIndex: 1,
    explanation: "'yield' pauses the function and produces a value, resuming from that point on the next call.",
  },

  // ---------------- C ----------------
  {
    id: "c-e1",
    courseId: "c",
    difficulty: "Easy",
    title: "Printing Output",
    prompt: "Which function is used to print output in C?",
    options: ["printf()", "print()", "cout", "echo()"],
    correctIndex: 0,
    explanation: "printf() is the standard C library function for formatted output.",
  },
  {
    id: "c-e2",
    courseId: "c",
    difficulty: "Easy",
    title: "Data Types",
    prompt: "Which data type is used to store a single character in C?",
    options: ["int", "char", "float", "string"],
    correctIndex: 1,
    explanation: "'char' stores a single character; C has no built-in 'string' type.",
  },
  {
    id: "c-e3",
    courseId: "c",
    difficulty: "Easy",
    title: "Statement Termination",
    prompt: "What is used to terminate a statement in C?",
    options: ["Colon", "Semicolon", "Period", "Comma"],
    correctIndex: 1,
    explanation: "Every C statement ends with a semicolon (;).",
  },
  {
    id: "c-m1",
    courseId: "c",
    difficulty: "Medium",
    title: "Pointers",
    prompt: "What does the '*' operator do when declaring a variable in C?",
    options: ["Multiplies a value", "Declares a pointer", "Declares an array", "Declares a constant"],
    correctIndex: 1,
    explanation: "Using '*' before a variable name declares it as a pointer.",
  },
  {
    id: "c-m2",
    courseId: "c",
    difficulty: "Medium",
    title: "Memory Allocation",
    prompt: "Which function dynamically allocates memory in C?",
    options: ["alloc()", "malloc()", "new", "create()"],
    correctIndex: 1,
    explanation: "malloc() allocates a block of memory on the heap at runtime.",
  },
  {
    id: "c-m3",
    courseId: "c",
    difficulty: "Medium",
    title: "Storage Classes",
    prompt: "Which storage class retains a variable's value between function calls?",
    options: ["auto", "static", "register", "extern"],
    correctIndex: 1,
    explanation: "'static' variables retain their value across multiple calls to the function.",
  },
  {
    id: "c-h1",
    courseId: "c",
    difficulty: "Hard",
    title: "Pointers to Pointers",
    prompt: "What does a double pointer (**ptr) represent?",
    options: ["A pointer to an array", "A pointer to a pointer", "A NULL pointer", "A constant pointer"],
    correctIndex: 1,
    explanation: "A double pointer stores the address of another pointer.",
  },
  {
    id: "c-h2",
    courseId: "c",
    difficulty: "Hard",
    title: "Memory Leaks",
    prompt: "What causes a memory leak in C?",
    options: ["Using too many variables", "Not freeing dynamically allocated memory", "Using global variables", "Using recursion"],
    correctIndex: 1,
    explanation: "Memory allocated with malloc()/calloc() that is never freed with free() causes a leak.",
  },
  {
    id: "c-h3",
    courseId: "c",
    difficulty: "Hard",
    title: "Function Pointers",
    prompt: "What is a function pointer used for in C?",
    options: [
      "Storing a function's return value",
      "Storing the address of a function so it can be called dynamically",
      "Declaring recursive functions",
      "Allocating memory",
    ],
    correctIndex: 1,
    explanation: "A function pointer holds a function's address, enabling callbacks and dynamic dispatch.",
  },

  // ---------------- C++ ----------------
  {
    id: "cpp-e1",
    courseId: "cpp",
    difficulty: "Easy",
    title: "Pointers Basics",
    prompt: "What does the '&' operator do when applied to a variable?",
    options: ["Dereferences a pointer", "Returns the memory address", "Declares a reference", "Performs bitwise AND"],
    correctIndex: 1,
    explanation: "'&' returns the address-of a variable.",
  },
  {
    id: "cpp-e2",
    courseId: "cpp",
    difficulty: "Easy",
    title: "Output Statement",
    prompt: "Which is used to print output in C++?",
    options: ["printf", "cout", "System.out", "print"],
    correctIndex: 1,
    explanation: "'cout' is the standard output stream object in C++ (from <iostream>).",
  },
  {
    id: "cpp-e3",
    courseId: "cpp",
    difficulty: "Easy",
    title: "Classes",
    prompt: "Which keyword is primarily used to define a class in C++?",
    options: ["struct", "class", "object", "define"],
    correctIndex: 1,
    explanation: "'class' is the standard keyword for defining a class in C++.",
  },
  {
    id: "cpp-m1",
    courseId: "cpp",
    difficulty: "Medium",
    title: "Constructors",
    prompt: "What is a constructor used for in C++?",
    options: ["To destroy an object", "To initialize an object when it is created", "To copy a class definition", "To overload operators"],
    correctIndex: 1,
    explanation: "A constructor automatically runs when an object is created, to initialize its state.",
  },
  {
    id: "cpp-m2",
    courseId: "cpp",
    difficulty: "Medium",
    title: "References vs Pointers",
    prompt: "What is a key difference between a pointer and a reference in C++?",
    options: ["A reference can be null", "A reference cannot be reassigned once initialized", "A pointer must always be initialized", "There is no difference"],
    correctIndex: 1,
    explanation: "Once a reference is bound to a variable, it cannot be made to refer to a different variable.",
  },
  {
    id: "cpp-m3",
    courseId: "cpp",
    difficulty: "Medium",
    title: "Operator Overloading",
    prompt: "Which C++ feature allows operators to work with user-defined types?",
    options: ["Inheritance", "Operator Overloading", "Templates", "Polymorphism"],
    correctIndex: 1,
    explanation: "Operator overloading lets you redefine how operators like +, -, == behave for custom classes.",
  },
  {
    id: "cpp-h1",
    courseId: "cpp",
    difficulty: "Hard",
    title: "Virtual Functions",
    prompt: "What is the purpose of a virtual function in C++?",
    options: ["To make a function run faster", "To enable runtime polymorphism", "To prevent function overriding", "To allocate memory dynamically"],
    correctIndex: 1,
    explanation: "Virtual functions allow a derived class's overridden method to be called through a base class pointer/reference at runtime.",
  },
  {
    id: "cpp-h2",
    courseId: "cpp",
    difficulty: "Hard",
    title: "Templates",
    prompt: "What is the main benefit of using templates in C++?",
    options: ["Faster compilation", "Writing generic, type-independent code", "Automatic memory management", "Simplifying inheritance"],
    correctIndex: 1,
    explanation: "Templates let you write functions/classes that work with any data type without rewriting code.",
  },
  {
    id: "cpp-h3",
    courseId: "cpp",
    difficulty: "Hard",
    title: "Smart Pointers",
    prompt: "What does std::unique_ptr guarantee?",
    options: [
      "Multiple owners can share the resource",
      "Only one owner holds the resource, which is auto-deleted when it goes out of scope",
      "The pointer never needs to be deleted",
      "It works only with arrays",
    ],
    correctIndex: 1,
    explanation: "unique_ptr provides exclusive ownership and automatically releases the resource when it goes out of scope.",
  },

  // ---------------- JAVASCRIPT ----------------
  {
    id: "js-e1",
    courseId: "javascript",
    difficulty: "Easy",
    title: "Console Output",
    prompt: "Which method logs output to the browser console?",
    options: ["console.log()", "print()", "echo()", "System.out.println()"],
    correctIndex: 0,
    explanation: "console.log() prints messages to the browser's or Node's console.",
  },
  {
    id: "js-e2",
    courseId: "javascript",
    difficulty: "Easy",
    title: "Variable Declaration",
    prompt: "Which keyword declares a block-scoped variable in JavaScript?",
    options: ["var", "let", "global", "define"],
    correctIndex: 1,
    explanation: "'let' declares a variable scoped to the nearest enclosing block, unlike 'var'.",
  },
  {
    id: "js-e3",
    courseId: "javascript",
    difficulty: "Easy",
    title: "Data Types",
    prompt: "Which of the following is a primitive data type in JavaScript?",
    options: ["Array", "Object", "Boolean", "Function"],
    correctIndex: 2,
    explanation: "Boolean is a primitive type; Array, Object, and Function are all objects in JavaScript.",
  },
  {
    id: "js-m1",
    courseId: "javascript",
    difficulty: "Medium",
    title: "Equality Operators",
    prompt: "What is the key difference between '==' and '===' in JavaScript?",
    options: [
      "'==' checks both value and type",
      "'===' checks both value and type, while '==' allows type coercion",
      "They behave identically",
      "'==' only works with numbers",
    ],
    correctIndex: 1,
    explanation: "'===' (strict equality) compares value and type without coercion; '==' converts types before comparing.",
  },
  {
    id: "js-m2",
    courseId: "javascript",
    difficulty: "Medium",
    title: "Closures",
    prompt: "What is a closure in JavaScript?",
    options: ["A function that has no parameters", "A function that remembers variables from its outer scope", "A loop that never ends", "A method to close a browser tab"],
    correctIndex: 1,
    explanation: "A closure is formed when an inner function retains access to its outer function's variables even after the outer function returns.",
  },
  {
    id: "js-m3",
    courseId: "javascript",
    difficulty: "Medium",
    title: "Promises",
    prompt: "What does a JavaScript Promise represent?",
    options: ["A synchronous function call", "The eventual completion (or failure) of an asynchronous operation", "A type of loop", "A CSS animation"],
    correctIndex: 1,
    explanation: "A Promise is an object representing the future result of an async operation, resolved or rejected.",
  },
  {
    id: "js-h1",
    courseId: "javascript",
    difficulty: "Hard",
    title: "Event Loop",
    prompt: "What allows JavaScript, a single-threaded language, to handle asynchronous operations?",
    options: ["Multiple threads", "The event loop", "Web Workers only", "Garbage collection"],
    correctIndex: 1,
    explanation: "The event loop manages the call stack and callback/microtask queues, enabling async behavior on a single thread.",
  },
  {
    id: "js-h2",
    courseId: "javascript",
    difficulty: "Hard",
    title: "Prototypal Inheritance",
    prompt: "How does inheritance primarily work in JavaScript?",
    options: ["Through classical class-based inheritance only", "Through the prototype chain", "Through multiple inheritance", "JavaScript does not support inheritance"],
    correctIndex: 1,
    explanation: "Objects inherit properties/methods from other objects via the prototype chain, even when 'class' syntax is used.",
  },
  {
    id: "js-h3",
    courseId: "javascript",
    difficulty: "Hard",
    title: "Hoisting",
    prompt: "What does 'hoisting' mean in JavaScript?",
    options: [
      "Variable and function declarations are conceptually moved to the top of their scope",
      "Variables are deleted automatically",
      "Functions run in reverse order",
      "Code is minified automatically",
    ],
    correctIndex: 0,
    explanation: "Declarations are processed before code execution, so they can be referenced before their line in the code (with different behavior for var/let/const).",
  },

  // ---------------- DATA STRUCTURES ----------------
  {
    id: "dsa-e1",
    courseId: "dsa",
    difficulty: "Easy",
    title: "Array Access",
    prompt: "What is the time complexity to access an element by index in an array?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"],
    correctIndex: 0,
    explanation: "Arrays support direct indexed access, so it takes constant time O(1).",
  },
  {
    id: "dsa-e2",
    courseId: "dsa",
    difficulty: "Easy",
    title: "Stack Operations",
    prompt: "Which operation adds an element to the top of a stack?",
    options: ["Enqueue", "Push", "Pop", "Dequeue"],
    correctIndex: 1,
    explanation: "'Push' adds an element to the top of a stack (LIFO structure).",
  },
  {
    id: "dsa-e3",
    courseId: "dsa",
    difficulty: "Easy",
    title: "Linked List Basics",
    prompt: "What does each node in a singly linked list contain?",
    options: ["Only data", "Data and a pointer to the next node", "Two pointers only", "Data and an index"],
    correctIndex: 1,
    explanation: "Each node stores its data plus a reference/pointer to the next node in the list.",
  },
  {
    id: "dsa-m1",
    courseId: "dsa",
    difficulty: "Medium",
    title: "Stack vs Queue",
    prompt: "Which data structure follows First-In-First-Out (FIFO)?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    correctIndex: 1,
    explanation: "A Queue processes elements in the order they were added (FIFO).",
  },
  {
    id: "dsa-m2",
    courseId: "dsa",
    difficulty: "Medium",
    title: "Binary Trees",
    prompt: "In a binary tree, what is the maximum number of children a node can have?",
    options: ["1", "2", "3", "Unlimited"],
    correctIndex: 1,
    explanation: "By definition, each node in a binary tree has at most two children.",
  },
  {
    id: "dsa-m3",
    courseId: "dsa",
    difficulty: "Medium",
    title: "Hashing",
    prompt: "What is a hash collision?",
    options: [
      "When a hash function returns different outputs for the same input",
      "When two different keys map to the same index/slot",
      "When a hash table runs out of memory",
      "When a key is deleted",
    ],
    correctIndex: 1,
    explanation: "A collision occurs when two distinct keys hash to the same bucket/index.",
  },
  {
    id: "dsa-h1",
    courseId: "dsa",
    difficulty: "Hard",
    title: "Binary Search Complexity",
    prompt: "What is the time complexity of binary search on a sorted array?",
    options: ["O(n)", "O(n log n)", "O(log n)", "O(1)"],
    correctIndex: 2,
    explanation: "Binary search halves the search space each step, giving O(log n).",
  },
  {
    id: "dsa-h2",
    courseId: "dsa",
    difficulty: "Hard",
    title: "Balanced Trees",
    prompt: "What is the main advantage of a self-balancing tree like AVL over a plain BST?",
    options: ["Uses less memory", "Guarantees O(log n) operations by keeping the height balanced", "Allows duplicate keys", "Is easier to implement"],
    correctIndex: 1,
    explanation: "AVL trees rebalance after insertions/deletions, keeping height logarithmic and operations efficient.",
  },
  {
    id: "dsa-h3",
    courseId: "dsa",
    difficulty: "Hard",
    title: "Graph Traversal",
    prompt: "Which traversal technique uses a queue and explores neighbors level by level?",
    options: ["DFS", "BFS", "In-order traversal", "Post-order traversal"],
    correctIndex: 1,
    explanation: "Breadth-First Search (BFS) uses a queue to visit nodes level by level.",
  },

  // ---------------- ALGORITHMS ----------------
  {
    id: "algo-e1",
    courseId: "algorithms",
    difficulty: "Easy",
    title: "Sorting Basics",
    prompt: "Which sorting algorithm repeatedly swaps adjacent elements if they are in the wrong order?",
    options: ["Bubble Sort", "Quick Sort", "Merge Sort", "Heap Sort"],
    correctIndex: 0,
    explanation: "Bubble Sort compares and swaps adjacent elements repeatedly until the list is sorted.",
  },
  {
    id: "algo-e2",
    courseId: "algorithms",
    difficulty: "Easy",
    title: "Searching Basics",
    prompt: "What is required for binary search to work correctly?",
    options: ["The array must be sorted", "The array must contain unique elements", "The array must be an integer array", "The array must be reversed"],
    correctIndex: 0,
    explanation: "Binary search relies on the array being sorted to eliminate half the search space each step.",
  },
  {
    id: "algo-e3",
    courseId: "algorithms",
    difficulty: "Easy",
    title: "Big O Basics",
    prompt: "What does Big O notation describe?",
    options: ["The exact runtime of an algorithm in seconds", "The upper bound / growth rate of an algorithm's time or space usage", "The programming language used", "The number of lines of code"],
    correctIndex: 1,
    explanation: "Big O describes how an algorithm's resource usage grows relative to input size, not exact timing.",
  },
  {
    id: "algo-m1",
    courseId: "algorithms",
    difficulty: "Medium",
    title: "Recursion",
    prompt: "What must every recursive function have to avoid infinite recursion?",
    options: ["A loop", "A base case", "A pointer", "A global variable"],
    correctIndex: 1,
    explanation: "A base case stops the recursive calls once a simple condition is met.",
  },
  {
    id: "algo-m2",
    courseId: "algorithms",
    difficulty: "Medium",
    title: "Divide and Conquer",
    prompt: "Which algorithm design technique does Merge Sort use?",
    options: ["Greedy", "Divide and Conquer", "Dynamic Programming", "Backtracking"],
    correctIndex: 1,
    explanation: "Merge Sort splits the array, recursively sorts the halves, then merges them — a classic divide and conquer approach.",
  },
  {
    id: "algo-m3",
    courseId: "algorithms",
    difficulty: "Medium",
    title: "Greedy Algorithms",
    prompt: "Greedy algorithms make decisions based on:",
    options: ["Trying every possible option", "The locally optimal choice at each step", "Random selection", "Pre-computed results only"],
    correctIndex: 1,
    explanation: "Greedy algorithms pick the best available option at each step, hoping it leads to a global optimum.",
  },
  {
    id: "algo-h1",
    courseId: "algorithms",
    difficulty: "Hard",
    title: "Dynamic Programming",
    prompt: "What is the key idea behind Dynamic Programming?",
    options: ["Always choosing the locally best option", "Breaking a problem into overlapping subproblems and storing their results", "Randomizing the input", "Using recursion without any base case"],
    correctIndex: 1,
    explanation: "DP solves overlapping subproblems once and reuses (memoizes) their results to avoid recomputation.",
  },
  {
    id: "algo-h2",
    courseId: "algorithms",
    difficulty: "Hard",
    title: "NP-Completeness",
    prompt: "What does it mean for a problem to be NP-Complete?",
    options: ["It can be solved in polynomial time", "No known polynomial-time algorithm solves it, but a solution can be verified in polynomial time", "It cannot be verified at all", "It is always unsolvable"],
    correctIndex: 1,
    explanation: "NP-Complete problems are the hardest in NP — verifiable quickly, but no efficient solving algorithm is known.",
  },
  {
    id: "algo-h3",
    courseId: "algorithms",
    difficulty: "Hard",
    title: "Sorting Complexity",
    prompt: "What is the average-case time complexity of Quick Sort?",
    options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"],
    correctIndex: 1,
    explanation: "Quick Sort averages O(n log n), though its worst case is O(n^2) with poor pivot choices.",
  },

  // ---------------- DBMS / SQL ----------------
  {
    id: "dbms-e1",
    courseId: "dbms",
    difficulty: "Easy",
    title: "SQL Basics",
    prompt: "Which SQL statement is used to retrieve data from a database?",
    options: ["GET", "SELECT", "FETCH", "RETRIEVE"],
    correctIndex: 1,
    explanation: "SELECT is the standard SQL statement for querying and retrieving data.",
  },
  {
    id: "dbms-e2",
    courseId: "dbms",
    difficulty: "Easy",
    title: "Primary Key",
    prompt: "What is the main purpose of a primary key in a table?",
    options: ["To store large text", "To uniquely identify each row in a table", "To sort the table alphabetically", "To speed up all queries automatically"],
    correctIndex: 1,
    explanation: "A primary key uniquely identifies each row and cannot contain duplicate or NULL values.",
  },
  {
    id: "dbms-e3",
    courseId: "dbms",
    difficulty: "Easy",
    title: "Filtering Rows",
    prompt: "Which SQL clause is used to filter rows based on a condition?",
    options: ["ORDER BY", "WHERE", "GROUP BY", "HAVING"],
    correctIndex: 1,
    explanation: "WHERE filters individual rows before any grouping is applied.",
  },
  {
    id: "dbms-m1",
    courseId: "dbms",
    difficulty: "Medium",
    title: "Joins",
    prompt: "Which JOIN returns only the matching rows from both tables?",
    options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN"],
    correctIndex: 2,
    explanation: "INNER JOIN returns only rows that have matching values in both joined tables.",
  },
  {
    id: "dbms-m2",
    courseId: "dbms",
    difficulty: "Medium",
    title: "Normalization",
    prompt: "What is the main goal of normalization in database design?",
    options: ["To increase data redundancy", "To reduce data redundancy and improve data integrity", "To make queries slower", "To delete unused tables"],
    correctIndex: 1,
    explanation: "Normalization organizes data to minimize redundancy and dependency issues.",
  },
  {
    id: "dbms-m3",
    courseId: "dbms",
    difficulty: "Medium",
    title: "Aggregate Functions",
    prompt: "Which clause groups rows sharing a property so aggregate functions can be applied?",
    options: ["WHERE", "GROUP BY", "ORDER BY", "HAVING"],
    correctIndex: 1,
    explanation: "GROUP BY groups rows with the same values, typically used with aggregate functions like COUNT() or SUM().",
  },
  {
    id: "dbms-h1",
    courseId: "dbms",
    difficulty: "Hard",
    title: "Transactions (ACID)",
    prompt: "What does the 'A' in the ACID properties of a transaction stand for?",
    options: ["Availability", "Atomicity", "Authentication", "Aggregation"],
    correctIndex: 1,
    explanation: "Atomicity ensures a transaction is all-or-nothing — it fully completes or fully rolls back.",
  },
  {
    id: "dbms-h2",
    courseId: "dbms",
    difficulty: "Hard",
    title: "Indexing",
    prompt: "What is the main trade-off of adding an index to a table?",
    options: ["Faster reads but slower writes/inserts", "Slower reads but faster writes", "No effect on performance", "Indexes only work on primary keys"],
    correctIndex: 0,
    explanation: "Indexes speed up lookups but add overhead to insert/update/delete operations since the index must be maintained.",
  },
  {
    id: "dbms-h3",
    courseId: "dbms",
    difficulty: "Hard",
    title: "Normal Forms",
    prompt: "A table that is in 2NF and additionally has no transitive dependencies is said to be in which normal form?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    correctIndex: 2,
    explanation: "3NF requires 2NF plus the elimination of transitive dependencies on the primary key.",
  },

  // ---------------- OOP CONCEPTS ----------------
  {
    id: "oop-e1",
    courseId: "oop",
    difficulty: "Easy",
    title: "Core Concepts",
    prompt: "Which of these is NOT one of the four pillars of OOP?",
    options: ["Encapsulation", "Inheritance", "Compilation", "Polymorphism"],
    correctIndex: 2,
    explanation: "The four pillars are Encapsulation, Inheritance, Polymorphism, and Abstraction. Compilation is unrelated.",
  },
  {
    id: "oop-e2",
    courseId: "oop",
    difficulty: "Easy",
    title: "Classes and Objects",
    prompt: "What is an object in OOP?",
    options: ["A blueprint for creating instances", "An instance of a class", "A type of loop", "A function"],
    correctIndex: 1,
    explanation: "An object is a concrete instance created from a class (the blueprint).",
  },
  {
    id: "oop-e3",
    courseId: "oop",
    difficulty: "Easy",
    title: "Encapsulation",
    prompt: "What does encapsulation mean in OOP?",
    options: ["Combining data and methods into a single unit and restricting direct access", "Allowing multiple classes to inherit from one class", "Overriding a method", "Writing code without functions"],
    correctIndex: 0,
    explanation: "Encapsulation bundles data with the methods that operate on it, hiding internal details behind access modifiers.",
  },
  {
    id: "oop-m1",
    courseId: "oop",
    difficulty: "Medium",
    title: "Inheritance",
    prompt: "What is the main benefit of inheritance in OOP?",
    options: ["It hides all data permanently", "It allows a class to reuse fields and methods of another class", "It prevents code reuse", "It makes classes immutable"],
    correctIndex: 1,
    explanation: "Inheritance lets a subclass reuse and extend the behavior of a parent class.",
  },
  {
    id: "oop-m2",
    courseId: "oop",
    difficulty: "Medium",
    title: "Polymorphism",
    prompt: "Method overriding is an example of which kind of polymorphism?",
    options: ["Compile-time polymorphism", "Runtime polymorphism", "Encapsulation", "Abstraction"],
    correctIndex: 1,
    explanation: "Overriding resolves which method runs at runtime based on the actual object type, making it runtime polymorphism.",
  },
  {
    id: "oop-m3",
    courseId: "oop",
    difficulty: "Medium",
    title: "Abstraction",
    prompt: "What is the purpose of an abstract class?",
    options: ["To be instantiated directly and used everywhere", "To define a common template while hiding implementation details from subclasses", "To store only static data", "To replace interfaces entirely"],
    correctIndex: 1,
    explanation: "Abstract classes define shared structure/behavior and force subclasses to implement specific details.",
  },
  {
    id: "oop-h1",
    courseId: "oop",
    difficulty: "Hard",
    title: "Overloading vs Overriding",
    prompt: "What best distinguishes method overloading from method overriding?",
    options: [
      "Overloading happens at runtime, overriding at compile time",
      "Overloading has the same method name with different parameters in the same class; overriding redefines a method in a subclass",
      "They are the same concept",
      "Overriding requires no inheritance",
    ],
    correctIndex: 1,
    explanation: "Overloading is compile-time (same class, different signatures); overriding is runtime (subclass redefines a parent method).",
  },
  {
    id: "oop-h2",
    courseId: "oop",
    difficulty: "Hard",
    title: "Interfaces vs Abstract Classes",
    prompt: "What is a key difference between an interface and an abstract class in languages like Java?",
    options: [
      "Interfaces can have constructors",
      "A class can implement multiple interfaces but typically extend only one abstract class",
      "Abstract classes cannot have any methods",
      "Interfaces cannot be used for polymorphism",
    ],
    correctIndex: 1,
    explanation: "Java doesn't support multiple class inheritance, but a class can implement several interfaces.",
  },
  {
    id: "oop-h3",
    courseId: "oop",
    difficulty: "Hard",
    title: "Coupling and Cohesion",
    prompt: "In good OOP design, what should you aim for?",
    options: ["High coupling and low cohesion", "Low coupling and high cohesion", "High coupling and high cohesion", "Coupling and cohesion do not matter"],
    correctIndex: 1,
    explanation: "Low coupling (minimal dependencies between classes) and high cohesion (focused responsibility per class) lead to maintainable design.",
  },

  // ---------------- WEB DEVELOPMENT ----------------
  {
    id: "webdev-e1",
    courseId: "webdev",
    difficulty: "Easy",
    title: "HTML Basics",
    prompt: "Which tag is used to create a hyperlink in HTML?",
    options: ["<link>", "<a>", "<href>", "<url>"],
    correctIndex: 1,
    explanation: "The <a> (anchor) tag with an href attribute creates a hyperlink.",
  },
  {
    id: "webdev-e2",
    courseId: "webdev",
    difficulty: "Easy",
    title: "CSS Basics",
    prompt: "Which CSS property changes the text color of an element?",
    options: ["background-color", "color", "font-color", "text-style"],
    correctIndex: 1,
    explanation: "The 'color' property sets the text (foreground) color.",
  },
  {
    id: "webdev-e3",
    courseId: "webdev",
    difficulty: "Easy",
    title: "HTML Structure",
    prompt: "Which tag represents the root of an HTML document?",
    options: ["<body>", "<html>", "<head>", "<root>"],
    correctIndex: 1,
    explanation: "<html> is the root element that contains the entire document, including <head> and <body>.",
  },
  {
    id: "webdev-m1",
    courseId: "webdev",
    difficulty: "Medium",
    title: "Box Model",
    prompt: "Which part of the CSS box model surrounds the border on the outside?",
    options: ["Padding", "Margin", "Content", "Outline"],
    correctIndex: 1,
    explanation: "Margin is the outermost layer, creating space between an element and its neighbors.",
  },
  {
    id: "webdev-m2",
    courseId: "webdev",
    difficulty: "Medium",
    title: "Flexbox",
    prompt: "Which CSS declaration enables flexbox layout on a container?",
    options: ["display: flex;", "position: flex;", "layout: flex;", "flex: enable;"],
    correctIndex: 0,
    explanation: "Setting 'display: flex' on a container turns its direct children into flex items.",
  },
  {
    id: "webdev-m3",
    courseId: "webdev",
    difficulty: "Medium",
    title: "Responsive Design",
    prompt: "Which CSS feature allows different styles based on screen size?",
    options: ["Media queries", "Flexbox", "Pseudo-classes", "CSS variables"],
    correctIndex: 0,
    explanation: "Media queries apply CSS rules conditionally based on viewport width, device type, etc.",
  },
  {
    id: "webdev-h1",
    courseId: "webdev",
    difficulty: "Hard",
    title: "Specificity",
    prompt: "In CSS, which selector generally has the highest specificity?",
    options: ["Element selector", "Class selector", "ID selector", "Universal selector (*)"],
    correctIndex: 2,
    explanation: "ID selectors have higher specificity than class or element selectors (but lower than inline styles/!important).",
  },
  {
    id: "webdev-h2",
    courseId: "webdev",
    difficulty: "Hard",
    title: "Rendering",
    prompt: "What does the browser's Critical Rendering Path primarily describe?",
    options: ["How JavaScript is minified", "The steps a browser takes to convert HTML, CSS, and JS into pixels on screen", "How images are compressed", "How cookies are stored"],
    correctIndex: 1,
    explanation: "The Critical Rendering Path covers DOM/CSSOM construction, layout, and paint — the sequence to render a page.",
  },
  {
    id: "webdev-h3",
    courseId: "webdev",
    difficulty: "Hard",
    title: "CORS",
    prompt: "What does CORS control in web development?",
    options: ["How CSS is applied to a page", "Whether a web page can make requests to a different origin/domain", "How fonts are loaded", "Database query optimization"],
    correctIndex: 1,
    explanation: "Cross-Origin Resource Sharing (CORS) is a browser security mechanism controlling cross-origin HTTP requests.",
  },

  // ---------------- OPERATING SYSTEMS ----------------
  {
    id: "os-e1",
    courseId: "os",
    difficulty: "Easy",
    title: "OS Basics",
    prompt: "What is the primary function of an operating system?",
    options: ["To compile programs", "To manage hardware and software resources", "To design websites", "To create databases"],
    correctIndex: 1,
    explanation: "An OS manages CPU, memory, storage, and I/O devices, and provides services to applications.",
  },
  {
    id: "os-e2",
    courseId: "os",
    difficulty: "Easy",
    title: "Processes",
    prompt: "What is a process in an operating system?",
    options: ["A program in execution", "A type of file", "A hardware device", "A network protocol"],
    correctIndex: 0,
    explanation: "A process is an instance of a program currently being executed, with its own memory and resources.",
  },
  {
    id: "os-e3",
    courseId: "os",
    difficulty: "Easy",
    title: "Memory Basics",
    prompt: "What is RAM primarily used for?",
    options: ["Permanent storage", "Temporary storage for running programs", "Storing the OS installer", "Network communication"],
    correctIndex: 1,
    explanation: "RAM holds data and instructions for actively running programs; it is volatile and cleared on power-off.",
  },
  {
    id: "os-m1",
    courseId: "os",
    difficulty: "Medium",
    title: "Scheduling",
    prompt: "Which CPU scheduling algorithm can cause 'starvation' for longer processes?",
    options: ["Round Robin", "Shortest Job First (SJF)", "First-Come-First-Served", "FIFO"],
    correctIndex: 1,
    explanation: "SJF can repeatedly favor shorter jobs, causing longer processes to wait indefinitely (starvation).",
  },
  {
    id: "os-m2",
    courseId: "os",
    difficulty: "Medium",
    title: "Deadlock Conditions",
    prompt: "Which of these is NOT one of the four necessary conditions for deadlock?",
    options: ["Mutual Exclusion", "Hold and Wait", "Preemption allowed", "Circular Wait"],
    correctIndex: 2,
    explanation: "Deadlock requires 'No Preemption' (resources can't be forcibly taken), not preemption being allowed.",
  },
  {
    id: "os-m3",
    courseId: "os",
    difficulty: "Medium",
    title: "Memory Management",
    prompt: "What is 'paging' in operating systems used for?",
    options: ["Compiling code faster", "Dividing memory into fixed-size blocks to avoid external fragmentation", "Managing network packets", "Scheduling processes"],
    correctIndex: 1,
    explanation: "Paging divides physical/logical memory into fixed-size pages/frames, eliminating external fragmentation.",
  },
  {
    id: "os-h1",
    courseId: "os",
    difficulty: "Hard",
    title: "Virtual Memory",
    prompt: "What is the main purpose of virtual memory?",
    options: ["To make the CPU run faster", "To let programs use more memory than is physically available by using disk space", "To speed up disk read/write", "To replace RAM entirely"],
    correctIndex: 1,
    explanation: "Virtual memory extends usable memory by swapping data between RAM and disk as needed.",
  },
  {
    id: "os-h2",
    courseId: "os",
    difficulty: "Hard",
    title: "Synchronization",
    prompt: "What is the purpose of a semaphore in operating systems?",
    options: ["To format the disk", "To control access to shared resources by multiple processes/threads", "To compile code", "To manage user accounts"],
    correctIndex: 1,
    explanation: "Semaphores coordinate access to shared resources, preventing race conditions between processes/threads.",
  },
  {
    id: "os-h3",
    courseId: "os",
    difficulty: "Hard",
    title: "Thrashing",
    prompt: "What does 'thrashing' refer to in an operating system?",
    options: ["Excessive paging causing a drop in system performance", "A hardware failure", "A type of deadlock", "A network congestion issue"],
    correctIndex: 0,
    explanation: "Thrashing happens when the system spends more time swapping pages than executing actual processes.",
  },

  // ---------------- COMPUTER NETWORKS ----------------
  {
    id: "net-e1",
    courseId: "networks",
    difficulty: "Easy",
    title: "IP Addresses",
    prompt: "What does IP stand for in networking?",
    options: ["Internet Protocol", "Internal Process", "Internet Package", "Interface Protocol"],
    correctIndex: 0,
    explanation: "IP (Internet Protocol) handles addressing and routing of packets across networks.",
  },
  {
    id: "net-e2",
    courseId: "networks",
    difficulty: "Easy",
    title: "OSI Model",
    prompt: "How many layers does the OSI model have?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
    explanation: "The OSI model has 7 layers, from Physical up to Application.",
  },
  {
    id: "net-e3",
    courseId: "networks",
    difficulty: "Easy",
    title: "Basic Terms",
    prompt: "What does a router primarily do?",
    options: ["Store files", "Forward data packets between different networks", "Display web pages", "Compile code"],
    correctIndex: 1,
    explanation: "Routers direct data packets between different networks based on IP addresses.",
  },
  {
    id: "net-m1",
    courseId: "networks",
    difficulty: "Medium",
    title: "TCP vs UDP",
    prompt: "Which protocol is connection-oriented and guarantees reliable delivery?",
    options: ["UDP", "TCP", "IP", "ARP"],
    correctIndex: 1,
    explanation: "TCP establishes a connection and ensures reliable, ordered delivery of data.",
  },
  {
    id: "net-m2",
    courseId: "networks",
    difficulty: "Medium",
    title: "DNS",
    prompt: "What is the main function of DNS?",
    options: ["To encrypt data", "To translate domain names into IP addresses", "To assign MAC addresses", "To manage firewalls"],
    correctIndex: 1,
    explanation: "DNS (Domain Name System) resolves human-readable domain names into IP addresses.",
  },
  {
    id: "net-m3",
    courseId: "networks",
    difficulty: "Medium",
    title: "HTTP Basics",
    prompt: "Which HTTP method is typically used to retrieve data without modifying it?",
    options: ["POST", "GET", "DELETE", "PUT"],
    correctIndex: 1,
    explanation: "GET requests retrieve data from a server and should not modify server state.",
  },
  {
    id: "net-h1",
    courseId: "networks",
    difficulty: "Hard",
    title: "Subnetting",
    prompt: "What is the purpose of subnetting a network?",
    options: ["To increase internet speed", "To divide a large network into smaller, manageable sub-networks", "To encrypt all traffic", "To assign domain names"],
    correctIndex: 1,
    explanation: "Subnetting splits a network into smaller segments for better organization, security, and address management.",
  },
  {
    id: "net-h2",
    courseId: "networks",
    difficulty: "Hard",
    title: "Three-Way Handshake",
    prompt: "What is the correct order of TCP's three-way handshake?",
    options: ["ACK, SYN, SYN-ACK", "SYN, SYN-ACK, ACK", "SYN-ACK, SYN, ACK", "ACK, SYN, SYN-ACK"],
    correctIndex: 1,
    explanation: "The client sends SYN, the server replies SYN-ACK, and the client confirms with ACK to establish a connection.",
  },
  {
    id: "net-h3",
    courseId: "networks",
    difficulty: "Hard",
    title: "Congestion Control",
    prompt: "Which of these is a TCP congestion control mechanism?",
    options: ["Round-robin scheduling", "Slow start", "DNS caching", "Subnet masking"],
    correctIndex: 1,
    explanation: "'Slow start' gradually increases the amount of data sent to avoid overwhelming the network.",
  },
];
